# Ask user to enter their name
name = input("What is your name human")
print(f"It is nice to meet you human {name}")

print("\t##########")
print("\t#        #")
print("\t#        #")
print("  ##############")
print("  #            #")
print("  #            #")
print("  #            #")
print("  #            #")
print("  ##############")

eye=input("please enter a character for the eye")
print("Beep's expression is now as follows")
print("#######")
print(f"#{eye}   {eye}#")
print("# --- #")
print("#######")